экономические:
    Кроны:
      - сообщение: "Проблемы с поступлением наличных, похоже что расходы слишком велики"
      - сообщение: "Есть идея продать часть сырья на рынке чтобы компенсировать потери в кронах"
      - сообщение: "Если мы не придумаем что нам делать с поступлением крон в казну, рискуем отстать в развитии"
      - сообщение: "У нас слишком большие расходы, нужно придумать как увеличить доход, может налоги повысим?"
      - сообщение: "Нужно пересмотреть наши торговые соглашения у нас дохера расходов"
      - сообщение: "Кроны надо было назвать песчинки, потому что они утекают с наших счетов как песок сквозь пальцы"
    Сырье:
      - сообщение: "Постой как это получилось?"
      - сообщение: "Не я все понимаю, смешно конечно, но где наше сырье?"
      - сообщение: "Я ни на что не намекаю, но раз у нас взялись проблемы там где их быть не должно, то можно сторговаться на рынке?"
      - сообщение: "Куда все сырье подевалось? Не пора бы нам заключить соглашение о поставках с Халидоном?"
      - сообщение: "Я не хочу показаться грубым, но сырье обычно добывают фабрики, это так, для справки"
    Население:
      - сообщение: "Нас становится все меньше, нужны больницы князь"
      - сообщение: "Демография страдает Ваше Величество, нужно что-то придумать, может больше больниц?"
      - сообщение: "Я бы рассмотрел вариант торгового соглашения о поставках рабочих, но проблема сырья все равно будет на нас"
      - сообщение: "Мы вымираем, нам нужно что-то делать, это влияет и на нашу казну"
      - сообщение: "Так и кануть в лету недолго"
      - сообщение: "Как думаете история будет к нам благосклонна? Люди умирают"
    Рабочие:
      - сообщение: "Похоже у нас не очень с рабочими местами, я встретил человека на улице и он послал меня нахер из-за отсутствия работы"
      - сообщение: "Надо бы больше больниц, занятость такая, что по сути нам некого мобилизовывать в случае чего"
      - сообщение: "В конце концов это влияет и на доход"
      - сообщение: "Надо быть расторопнее в экономике, а то нами пол вытрут"
политические:
      - сообщение: "Соседнее княжество предлагает альянс."
военные:
      - сообщение: "Армия готова к бою."
      - сообщение: "Армия ослаблена. Срочно нужны ресурсы."

